### ISSUE TITLE
Print from tests and buffered output on jenkins.

### ISSUE THREAD

**Issue by mwalkowski** [xmlrunner/unittest-xml-reporting#113]
After tests start all print function are disabled and does not work. Which is confusing when you are use setUpClass and tearDownClass method to wait for external dependences.
And on jenkis verbose is buffered and displayed after all tests executions, not step by step like in unittest. Which is also confusing because you don't know that test is hangs up.

**Comment by shaiksulaiman** [comment]
When running python unittest using XMLTestRunner, the output of the tests is not shown in real-time unlike TextTestRunner. 

Whole output is shown after the entire tests complete.  Support to redirect output to sys.stdout will be very helpful. 

Thanks for your efforts!

**Comment by dnozay** [comment]
@mwalkowski @shaiksulaiman, tests to exercise / verify this behavior; as well as pull requests are welcome.

**Comment by joevgear** [comment]
I was having the same issue and could not resolve until i looked into the code.  At first i thought it might be the flush() solution.  However the flush is not necessary the code already has a .showAll property that is exposed via the verbosity property.  If you set this property something to something >= 2 then you should see the output at run time.  Without it on my jenkins slave i would see output until the end.  Once i added it the output was displayed as the test were run.  

 runner = XMLTestRunner(output='/doctest_outputs', verbosity=2)

**Comment by RemcoTukker** [comment]
The [commit from peniblec](https://github.com/peniblec/unittest-xml-reporting/commit/3faacb71a049ff425bad267ca70779dfdb831ab0) fixes this issue, the buffer argument isn't passed on to the result.

**Comment by ikedam** [comment]
I believe #166 will resolve this issue.
It's merged but not released yet.

And this issue looks duplicate or be duplicated by #156.
