### ISSUE TITLE
xml stylesheets

### ISSUE THREAD

**Issue by greenpau** [xmlrunner/unittest-xml-reporting#114]
I am viewing unittests reports in Circle CI.

![image](https://cloud.githubusercontent.com/assets/3826416/12151237/2c20f85c-b47c-11e5-8aa8-27ed2de5cab0.png)

It is not pretty, because there are no stylesheets.

Is there a way to add a stylesheet to the reports?

**Comment by dnozay** [comment]
@greenpau, while people can certainly open an xml report, the report is meant to be machine-readable. You will need to file an issue with Circle CI so they do post-processing.
