### ISSUE TITLE
Passing stream to test runner gives TypeError

### ISSUE THREAD

**Issue by lowjoel** [xmlrunner/unittest-xml-reporting#123]
```
Traceback (most recent call last):
  File "tests/test_autograde_runes.py", line 73, in <module>
    catchbreak=False)
  File "/usr/lib/python3.4/unittest/main.py", line 93, in __init__
    self.runTests()
  File "/usr/lib/python3.4/unittest/main.py", line 244, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/local/lib/python3.4/dist-packages/xmlrunner/runner.py", line 111, in run
    result.generate_reports(self)
  File "/usr/local/lib/python3.4/dist-packages/xmlrunner/result.py", line 476, in generate_reports
    test_runner.output.write(xml_content)
TypeError: must be str, not bytes
```

One workaround (not sure if it is correct) is to change `test_runner.output.write(xml_content)` to `test_runner.output.write(xml_content.decode('utf-8'))`

**Comment by lowjoel** [comment]
I've since figured out that it's possible to use a binary stream which avoids this problem, too.

**Comment by dnozay** [comment]
@lowjoel, you just put a stacktrace there, without explaining what your input is, or how to reproduce your error. I am not sure what should be documented here. Could you please clarify?

**Comment by lowjoel** [comment]
Woops, sorry. I was supposed to get back to this.

This is the entry point:

```python
if __name__ == '__main__':
    unittest.main(
            testRunner=xmlrunner.XMLTestRunner(open('report.xml', 'wb'), outsuffix = ''),
            failfast=False,
            buffer=False,
            catchbreak=False)
```

I just moved to this package after noticing that this is being maintained and the old one was not.

**Comment by dnozay** [comment]
Please replace `open('report.xml', 'w')` with `open('report.xml', 'wb')`

**Comment by lowjoel** [comment]
Yes, that's what I did in the end.

Is passing a stream into the test runner constructor a supported configuration?

**Comment by dnozay** [comment]
yes.
