### ISSUE TITLE
xmlrunner module is not installed for Python 3

### ISSUE THREAD

**Issue by pmensik** [xmlrunner/unittest-xml-reporting#137]
I tried to install xmlrunner both from Debian package and through pip and I still have an error during import. 

So this is what I have tried 

    sudo apt-get install python-xmlrunner
    # this installs version 1.5.0-1

I also tried

    sudo pip install unittest-xml-reporting
    # Requirement already satisfied (use --upgrade to upgrade): unittest-xml-reporting in /usr/lib/python2.7/dist-packages

And finally the test

     python3
     >>> import xmlrunner
    ImportError: No module named 'xmlrunner'

I tried it on both Debian Jessie and elementary OS (Freya) so am I doing something wrong? btw I would prefer installing from .deb package because I don't have to install pip on machines which doesn't have it.

**Comment by benjaesq** [comment]
I believe you need to use pip3 or find the .deb for python3, both your install lines are for python2

**Comment by dnozay** [comment]
Welcome to open source software.

`python-xmlrunner` != `unittest-xml-reporting`.
https://packages.debian.org/sid/python/python-xmlrunner

These are forks maintained separately.
