### ISSUE TITLE
Setting properties for multiple test suites

### ISSUE THREAD

**Issue by eduardoreynoso** [xmlrunner/unittest-xml-reporting#141]
Hi!, Im trying to get an XML report with the following structure:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
   <testsuite errors="0" failures="0" name="admin.admin_spots_tests.AdminSpotsTests" skipped="0" tests="1" time="2.235">
      <properties>
         <property name="test_create_spot" value="101" />
      </properties>
      <testcase classname="admin.admin_spots_tests.AdminSpotsTests" name="test_create_spot" time="2.235" />
   </testsuite>
   <testsuite errors="0" failures="0" name="rentals.rentals_search_tests.RentalsSearchTests" skipped="0" tests="1" time="2.198">
      <properties>
         <property name="test_search_by_rental_id" value="201" />
      </properties>
      <testcase classname="rentals.rentals_search_tests.RentalsSearchTests" name="test_search_by_rental_id" time="2.198" />
   </testsuite>
</testsuites>
```

Where I want to set in the test suite properties, a list of IDs (for my test case management system).
I am creating a test suite (master test suite) and I add multiple test suites (child test suites) that contain one or many test cases.

The problem is that when I set the properties for a child test suite, its not showing in the XML.
If I set the properties of the master test suite, it does show but it adds the same property tags to every child test suite.
Any help is appreciated, thanks!

-Eduardo Reynoso

**Comment by dnozay** [comment]
Hi @eduardoreynoso, can you please point me to an existing schema?
Preferably a valid one used by a popular xUnit reporter.
