### ISSUE TITLE
Add param to the module to set the output directory

### ISSUE THREAD

**Issue by xmedeko** [xmlrunner/unittest-xml-reporting#143]
What about to add a param like ``--xmloutput dir`` to the module ``__main__.py`` so as it may be run as:
```
python -m xmlrunner  --xmloutput test-reports test_module
```

I may submit a PR if you agree with this change.

**Comment by dnozay** [comment]
Hi @xmedeko, that would be good. Please include tests.

**Comment by sanbales** [comment]
Just wondering what the status of this pull request is.  For what is worth, I think this would be a good feature to implement.

**Comment by xmedeko** [comment]
@sanbales move your comment to the PR #144, this  is an issue.
