### ISSUE TITLE
post-printing of the test name

### ISSUE THREAD

**Issue by benjaesq** [xmlrunner/unittest-xml-reporting#145]
Hi, I am looking at an issue filed here:

https://bugzilla.yoctoproject.org/show_bug.cgi?id=11060

where there is a difference between using standard unittest custom text test runner or this xml reporter. The difference is that the xml reporter does post printing of the test name instead of of pre-printing of it like unittest does it by default.

How would you advise to achieve it?

**Comment by dnozay** [comment]
@benjaesq can you please post a snippet of the differences?
What verbosity level are you using?
