### ISSUE TITLE
could not find a version that satisfies the requirement unittest-xml-reporting (from versions: )

### ISSUE THREAD

**Issue by anand853** [xmlrunner/unittest-xml-reporting#150]
collecting unittest-xml-reporting
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x106366c90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /artifactory/api/pypi/python/simple/unittest-xml-reporting/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x106366950>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /artifactory/api/pypi/python/simple/unittest-xml-reporting/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x106366bd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /artifactory/api/pypi/python/simple/unittest-xml-reporting/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x106366cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /artifactory/api/pypi/python/simple/unittest-xml-reporting/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x106366710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /artifactory/api/pypi/python/simple/unittest-xml-reporting/
  Could not find a version that satisfies the requirement unittest-xml-reporting (from versions: )
No matching distribution found for unittest-xml-reporting

**Comment by dnozay** [comment]
This is not the correct issue tracker for `pip install` issues.
AFAICT, you are also using artifactory, which we are not going to provide support in this issue tracker.
