### ISSUE TITLE
xml_content can be undefined when all_results is empty

### ISSUE THREAD

**Issue by sieira** [xmlrunner/unittest-xml-reporting#151]
If all_results is empty xml_content gets never defined, causing a difficult to understand error message

https://github.com/xmlrunner/unittest-xml-reporting/blob/master/xmlrunner/result.py#L493

**Comment by fozcode** [comment]
Specifically this error:

    Running tests...
    ----------------------------------------------------------------------
    ----------------------------------------------------------------------
    Ran 0 tests in 0.000s
    OK

    Generating XML reports...
    Traceback (most recent call last):
    ....
    File "..../lib/python3.5/site-packages/xmlrunner/result.py", line 567, in generate_reports
      test_runner.output.write(xml_content)
    UnboundLocalError: local variable 'xml_content' referenced before assignment

**Comment by dnozay** [comment]
fixed in cbbb6f2235c9c6ea16f94157c16236cd6dee1574
