### ISSUE TITLE
TEST_OUTPUT_DESCRIPTIONS doesnt affect xml output under django

### ISSUE THREAD

**Issue by msheiny** [xmlrunner/unittest-xml-reporting#152]
So this might be a mis-understanding on my part but I thought that adding this setting (`TEST_OUTPUT_DESCRIPTIONS`) plus verbosity to `2` in my django settings would inject the docstrings into the xml. However, it seems to only affect the CLI output and not the XML.

Did I misunderstand what this feature does or have I possible hit a bug? If it's the later, I'll provide more data points to try and recreate.

Thanks!

**Comment by dnozay** [comment]
`TEST_OUTPUT_DESCRIPTIONS` controls what gets on `stdout`, either the test name (default) or the test name + description. This has no effect on the output xml files.
