### ISSUE TITLE
Always show stdout and stderr?

### ISSUE THREAD

**Issue by hblok** [xmlrunner/unittest-xml-reporting#156]
I always want to see the output to stdout and stderr in the console, as well as have both recorded to the XML file, also when a test passes.

However, regardless of what settings I use for buffer, verbosity, stdout and stderr only go to the xml report file if the test passes. If it fails, I see both in the console and the file. This can be isolated to the use of the XMLTestRunner. If that line is commented out in the example below, buffer works as documented and expected, and stdout / stderr are shown in the console.

I can consistently reproduce this on Python 2.7 and 3.4. 

Here is the example I'm running. (The _print(file=sys.stderr)_ works in Python 3 only).

```
class TestXmlRunner(unittest.TestCase):

  def test_hello(self):
    print('hello')
    print('hello stderr', file=sys.stderr)
    self.assertTrue(True)

if __name__ == '__main__':
    unittest.main(
        testRunner=xmlrunner.XMLTestRunner(output='/tmp/test-reports',
                                           verbosity=2, buffer=False),
        verbosity=2, buffer=False)

```

Help, comments, fixes welcome. Happy to contribute with a fix, if I know what to fix.

Regards,
hblok

**Comment by McMagnus** [comment]
Had the same problem, perhaps not exactly what you're looking for, but I used this in the main function before starting the runner:

  logging.basicConfig(stream=sys.stdout, level=logging.INFO)

I then output all output using a logger, not print.

**Comment by hblok** [comment]
I found yet another workaround: Use the static original sys._ _ stdout _ _ instead. It will not be high-jacked by the testrunner. E.g.  
  
    sys.__stdout__.write("hello")
    
    print("hello", file=sys.__stdout__)

**Comment by ikedam** [comment]
I believe #166 resolves this issue.
It's merged but not released yet.
