### ISSUE TITLE
testcase names in results for testcases created with FunctionTestCase are all the variable name 

### ISSUE THREAD

**Issue by FlashSheridan** [xmlrunner/unittest-xml-reporting#169]
I’m creating table-driven test cases in a loop with unittest.FunctionTestCase, and in the test-reports result file created by xmlrunner.XMLTestRunner, all the test case entries have the same name:

`	<testcase classname="" name="the_func" time="0.031" timestamp="2018-08-17T16:31:16"/>`
where  `the_func` is the loop variable I used.  I’ve differentiated the testcase description by setting it differently for each case; I’d appreciate it if the results could have the description as the name instead.

**Comment by dnozay** [comment]
@FlashSheridan, if you can contribute a testcase, I can take a look when I have time.
Thanks for the report.
