### ISSUE TITLE
timestamp attribute in testcase element

### ISSUE THREAD

**Issue by openbrian** [xmlrunner/unittest-xml-reporting#170]
I'm using the xUnit plugin of Jenkins and it's reporting an issue with the format of my test reports generated by unittest-xml-reporting.

INFO: [JUnit] - 180 test report file(s) were found with the pattern 'test-reports/*.xml' relative to '/var/lib/jenkins/jobs/sc/branches/CFR-519-.ir7qi63a90dt.ted-tests/workspace' for the testing framework 'JUnit'.

WARNING: The file '/var/lib/jenkins/jobs/sc/branches/CFR-519-.ir7qi63a90dt.ted-tests/workspace/test-reports/TEST-test_account_creation.test_account_creation-20180817131434.xml' is an invalid file.
WARNING: At line 3 of file:/var/lib/jenkins/jobs/sc/branches/CFR-519-.ir7qi63a90dt.ted-tests/workspace/test-reports/TEST-test_account_creation.test_account_creation-20180817131434.xml:cvc-complex-type.3.2.2: Attribute 'timestamp' is not allowed to appear in element 'testcase'.

I did some quick searching and this seems to be true.  See http://help.catchsoftware.com/display/ET/JUnit+Format

**Comment by openbrian** [comment]
A better definition of the junit file format. https://github.com/junit-team/junit5/blob/86b6b85ba8268024e9c13779d96090e92eb9ea11/platform-tests/src/test/resources/jenkins-junit.xsd

**Comment by dnozay** [comment]
please take it to the xunit-plugin dev who changed their schema.
https://github.com/jenkinsci/xunit-plugin/commit/ff61b8e19361e8229947961660a3ff07fc5f711f#diff-f0aa5d0196add2cce0dba06272b53c0f

**Comment by estyrke** [comment]
@dnozay The xunit-plugin simply started enforcing the schema. From the changelog:

> Version 2.0.0
> Breaking Changes
> I have introduce some schemas validation becase the large number of issues opened to xUnit plugin. Those issues are caused by custom attributes or XML DOM in the report generated by some user/tools report logger also if they declare to produce a valid report file. This cause me to spend a lot of time to investigate what is right and what is wrong and how to implement the XSL without it goes in error during transformation. 
> 
> Official supported JUnit schema are Ant junit and Maven Surefire).
> In case you are using a non java tools that declares to produce a JUnit compatible report, ensure the report respects one of the widely used supported schemas. If not than select as test type the build step "Custom Tool" and use this XSL as described here.

The fact of the matter is that unittest-xml-reporting violates the Ant JUnit schema, which in turn makes it highly unlikely that the xunit-plugin team would accomodate any changes in that regard. I would thus like to request that this issue be reopened.
