### ISSUE TITLE
API breaking changes between xmlrunner 1.5.0 and 2.2.0

### ISSUE THREAD

**Issue by icarpis** [xmlrunner/unittest-xml-reporting#175]
I want to emigrate from [xmlrunner](https://pypi.org/project/xmlrunner/) to [unittest-xml-reporting](https://pypi.org/project/unittest-xml-reporting/) and I wanted to know if there are API breaking changes between xmlrunner 1.5.0 and 2.2.0?

**Comment by dnozay** [comment]
Yes, hence the major version change. No more python 2.6 support.
