### ISSUE TITLE
Configure output from command line

### ISSUE THREAD

**Issue by konstantinmiller** [xmlrunner/unittest-xml-reporting#177]
I'm running tests in a Docker container in discovery mode like this: `python -m xmlrunner`, and would like to output to a specific directory which is a mounted volume, to get the tests out of the container and back into Azure DevOps.

Is there any way to influence the output directory (and maybe even file name) from the command line?

I browsed through the issues but it seems that all that try to add such a feature have been rejected. Is that correct? Or am I overseeing it?

**Comment by dnozay** [comment]
you can already do that:
`python -m xmlrunner -o /some/directory`
