### ISSUE TITLE
add resultclass property to class XMLTestRunner(TextTestRunner) in Python 3 xmlrunner

### ISSUE THREAD

**Issue by echobravo2** [xmlrunner/unittest-xml-reporting#181]
In Python2.7, 
the XMLTestRunner(TextTestRunner) has 'resultclass' class property that can be used to point sub-classed _XMLTestResult.

/usr/local/lib/python2.7/dist-packages/xmlrunner/runner.py
    def __init__(self, output='.', outsuffix=None, stream=sys.stderr,
                 descriptions=True, verbosity=1, elapsed_times=True,
                 failfast=False, buffer=False, encoding=UTF8,
                 **resultclass**=None):
        TextTestRunner.__init__(self, stream, descriptions, verbosity,
                                failfast=failfast, buffer=buffer)

......
        if resultclass is None:
            self.**resultclass** = _XMLTestResult
        else:
            self.**resultclass** = resultclass

    def _make_result(self):
        return **self.resultclass**(
            self.stream, self.descriptions, self.verbosity, self.elapsed_times
        )

In Python3.5, the 'resultclass' class property is not used anymore.
/usr/local/lib/python3.5/dist-packages/xmlrunner/xmlrunner.py

class XMLTestRunner(TextTestRunner):
    """ 
    A test runner class that outputs the results in JUnit like XML files.
    """
    def __init__(self, output='.', outsuffix=None, stream=sys.stderr,
                 descriptions=True, verbosity=1, elapsed_times=True):
        TextTestRunner.__init__(self, stream, descriptions, verbosity)

Appreciate adding resultclass property to the XMLTestRunner class in Python3

**Comment by dnozay** [comment]
The code is the same for all python version in master branch.
I'm not sure what versions you have installed on your systems, you can check with:
```
$ python -c 'import xmlrunner.version;print(xmlrunner.version.__version__)'
```
