### ISSUE TITLE
Improve XML output granularity for stdout and stderr

### ISSUE THREAD

**Issue by bracco23** [xmlrunner/unittest-xml-reporting#184]
I have several testsuites with several testcases and right now each testsuite have its own XML file with only one stdout and stderr tag with the output of every testcase.

I was looking for an option to have a separate stdout and stderr tag in each testcase, so basically going from 

```
<testsuite>
    <testcase></testcase>
    <testcase></testcase>
    <testcase></testcase>
    <system-out></system-out>
    <system-err></system-err>
</testsuite>
```

to

```
<testsuite>
    <testcase>
        <system-out></system-out>
        <system-err></system-err>
    </testcase>
    <testcase>
        <system-out></system-out>
        <system-err></system-err>
    </testcase>
    <testcase>
        <system-out></system-out>
        <system-err></system-err>
    </testcase>
</testsuite>
```

**Comment by dnozay** [comment]
Hi @bracco23 - can you please point to existing tools that can parse this schema?

**Comment by bracco23** [comment]
Hi @dnozay, a quick google search brought me to https://github.com/gastlygem/junitparser, a junit parser in python. If you take a look at the source, you will see that the _TestCase_ class has a _system_out_ and a _system_err_ property, which seems to suggest the ability to parse xml like the example I've given. I have not actually tried since I don't have an example, but I'll keep looking for other parser if you want.

**Comment by bracco23** [comment]
To better understand, here are the pieces of information I found, I have looked for a specification of the correct format of a JUnit XML file and I found this [stackoverflow question](https://stackoverflow.com/q/4922867/6397798) where, among on the answers, a link to an open source XSD is given ( [here](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) the file) and, also, an example of a full empty example file in [this answer](https://stackoverflow.com/a/9691131/6397798)

**Comment by bracco23** [comment]
Here is the pieces of information I found:

The JUnit XML test report is created by the Ant Maven formatter which uses [this schema](https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd) as official schema. 

An example output is this:

```
<?xml version="1.0" encoding="utf-8"?>
<testsuite name="str1234" time="str1234" tests="str1234" errors="str1234" skipped="str1234" failures="str1234" group="str1234">
  <properties>
    <property name="str1234" value="str1234" />
  </properties>
  <testcase name="str1234" classname="str1234" group="str1234" time="str1234">
    <failure message="str1234" type="str1234" time="str1234">str1234</failure>
    <rerunFailure message="str1234" type="str1234" time="str1234">str1234</rerunFailure>
    <flakyFailure message="str1234" type="str1234" time="str1234">str1234</flakyFailure>
    <skipped message="str1234">str1234</skipped>
    <error message="str1234" type="str1234">str1234</error>
    <rerunError message="str1234" type="str1234" time="str1234">str1234</rerunError>
    <flakyError message="str1234" type="str1234" time="str1234">str1234</flakyError>
    <system-out />
    <system-err />
  </testcase>
</testsuite>
```

**Comment by dnozay** [comment]
This project currently uses `unittest-xml-reporting/tests/vendor/jenkins/xunit-plugin/junit-10.xsd` as schema. 
It is up to the test runner and test code to decide how tests are run (sequentially, in parallel, etc). This can change how things land on `stdout` and `stderr`. 

Given `N tests` running in parallel and all fighting for `stdout` and `stderr` you would need to do more work to separate streams. This would be more complex, maybe more unreliable and give a false impression by hiding a class of issues related to concurrent access to those streams.
This is a trade-off, I like simple systems; they are easier to reason about.

The option does not exist currently, and I can't find older similar requests.
Can you please elaborate some more about the rationale behind more granular outputs?
PR welcome (with tests of course).

**Comment by bracco23** [comment]
Sorry, I didn't see the schema in the project code, but I'm glad to see that it considers valid the new proposed output too.

I think we can both agree that the purposes of a test report are keeping track of tests execution and aid in debugging failed tests, the main reason why stdout and stderr are included in the report.

With the current functionalities, if a test fail and the error message is not sufficient, the developer must either re-run the test or look among all the output of the suite. This process can be lengthy, especially if the suite is full of tests or the test takes time to run or the failing execution has taken place on a remote server, with a possibly different environment.

By separating the output of the tests, it will be easier for the developer to read the output of the failed test, speeding up this process.

**Comment by djmeck** [comment]
I also have a similar requirement. I think there is a way to address it while not deviating from the test report schema you have chosen.

One caveat is that the test report schema you are using contains contains attributes for 'testcase' that I cannot find on other junit test report schemas on the web.

It is exactly one of those fields, the 'log' field, that I feel could be used to report up specific information about failures or anything else that occur during the test.

**Comment by bracco23** [comment]
As long as I have seen, the actual schema used here should cover also having `system-out` and `system-err` under `testcase`.

**Comment by dnozay** [comment]
see ea89336df2800e072db701399dacb05f8dd68055
