### ISSUE TITLE
Keep all system output

### ISSUE THREAD

**Issue by XonqNopp** [xmlrunner/unittest-xml-reporting#192]
In the current state the XML shows `system-out` and `system-err` which only comes from the test themselves. We are currently printing important information in the setUpClass since they will be the same for the whole class and we need this in the output. (And of course at the same time tearDownClass could be of interest.)

**Comment by dnozay** [comment]
https://github.com/python/cpython/blob/2.7/Lib/unittest/suite.py
```
_call_if_exists(result, '_setupStdout')
```

You do get the output if there is a failure, because it will capture stdout and possibly do a skip or an error. However if things are successful, it does not call a method on the result, so there is nothing to hook into.

I'm not sure it's worth adding TBH; you would have to change the test discovery and use a different TestSuite object.

**Comment by XonqNopp** [comment]
We are running tests now and in the setUpClass we log the version of the FW of each device in use. Since we cannot keep it, we are not sure afterwards if it was the correct version. It would really help to be able to keep it.

But I don't get your comment... Why do you cite python2's unittest package? I am talking about what is stored in the XML. The console prints everything I want, it is only not stored in the XML...??

**Comment by XonqNopp** [comment]
Any new thoughts on this topic?

**Comment by dnozay** [comment]
- we use `unittest` internals under the hood.
- `unittest` throws away output when `setUpClass` is complete in its `try/finally` clause.

if you need to override this, you need a custom runner / test discovery that will change this.

> We are running tests now and in the setUpClass we log the version of the FW of each device in use. Since we cannot keep it

why is that? can't you save it on the test class and log it in the test?

**Comment by XonqNopp** [comment]
> why is that? can't you save it on the test class and log it in the test?

Seriously? Adding like 50 more output lines on *each* test log when it could be done only once?

**Comment by dnozay** [comment]
> Seriously? Adding like 50 more output lines on each test log when it could be done only once?

pull requests welcome.
