### ISSUE TITLE
Python 2.7 and __future__ unicode_literals

### ISSUE THREAD

**Issue by martync** [xmlrunner/unittest-xml-reporting#193]
Hi, 

I've a django project running on python 2.7.14 with many apps. Some of them are python 3 compatible, some aren't. 

The testcases with unicode docstrings (because of import __future__ unicode literals) are failing when running on atlassian bamboo. 

```
File "/Users/martyn/.virtualenvs/bamboo/lib/python2.7/site-packages/xmlrunner/result.py", line 279, in startTest
    self.stream.write('  ' + self.getDescription(test).encode("utf-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 91: ordinal not in range(128)
```

Because it's not possible to write unicode to a file. So a possible fix would be to encode the unicode string : 

https://github.com/xmlrunner/unittest-xml-reporting/blob/master/xmlrunner/result.py#L279
```
            description = self.getDescription(test)
            if type(description) == unicode:
                description = description.encode("utf-8")
            self.stream.write(" " + description)
```

Probably not the best way of doing it + I don't know about side effects but this fixes my issue.

**Comment by dnozay** [comment]
python 2 is EOL, not going to fix.
