### ISSUE TITLE
Readme Reporting to a single file

### ISSUE THREAD

**Issue by tbuerli** [xmlrunner/unittest-xml-reporting#196]
The example for Reporting to a single file doesn't work:

Error:
TypeError: a bytes-like object is required, not 'str'

The line:
    with open('/path/to/results.xml', 'wb') as output:
Should be changed to:
    with open('/path/to/results.xml', 'w') as output:

**Comment by worthlesspenny7** [comment]
@tbuerli  Check that you pip installed unittest-xml-reporting and not xmlrunner.  'wb' is the correct call for this module. The pypi package 'xmlrunner' is hundreds of commits behind this package (unittest-xml-reporting). 

Using 'wb' with unittest-xml-reporting (called in python as test_runner = xmlrunner) worked for me.
