### ISSUE TITLE
Not matching python unittest structure.

### ISSUE THREAD

**Issue by EltonZhong** [xmlrunner/unittest-xml-reporting#202]
I'm using unittest TestSuite with xmlrunner.
I got SuiteA with TestCaseB and TestCase C,

When I use xmlRunner.run(SuiteA),
I found that the report showes like below:
```xml
<testsuites>
<testsuite name=B>
<testcase .... TestCase B's methods>
<testsuite />
<testsuite name=C/>
</testsuites>
```

It's different from unittest structure.

**Comment by dnozay** [comment]
> It's different from unittest structure.

`unittest` does not produce xml, what structure are you expecting?
Please add code to reproduce or there is nothing really to work on.

**Comment by EltonZhong** [comment]
> > It's different from unittest structure.
> 
> `unittest` does not produce xml, what structure are you expecting?
> Please add code to reproduce or there is nothing really to work on.

I mean, when running SuiteA with TestCaseB and TestCase C,
I expect the output xml to be like:
```xml
<testsuite name=A>
    <testcase name=B/>
     <testcase name=C/>
</testsuite>
```

but actually outputs:
```xml
<testsuites>
    <testsuite name=B/>
    <testsuite name=C/>
</testsuites>
```

The code to reproduce 
```python
from unittest import TestSuite, TestCase

import xmlrunner


class TestB(TestCase):
    def test_b(self):
        self.assertTrue(1)


class TestC(TestCase):
    def test_c(self):
        self.assertTrue(0)




if __name__ == '__main__':
    suite = TestSuite()
    suite.addTests([TestB('test_b'), TestC('test_c')])
    runner = xmlrunner.XMLTestRunner(output=open('xx.xml', 'wb'))
    runner.run(suite)
```

**Comment by dnozay** [comment]
that is correct, junit concepts and python unittest concepts don't map 100%.

```
from unittest import TestSuite, TestCase

class MainTestcase(TestCase):
    def test_fn(self):
        for i in range(5):
            with self.subTest(f'iteration {i}'):
                assert i % 2
```
