### ISSUE TITLE
FYI, absl-py also contains a Python unittest xml reporter.

### ISSUE THREAD

**Issue by gpshead** [xmlrunner/unittest-xml-reporting#203]
absl-py's code lives in in https://github.com/abseil/abseil-py/tree/master/absl/testing.  It is a direct desendant of code we created internally at Google long long ago. This isn't a bug, I'm filing this as a cookie crumb to point out that another project offers this in case there is ever anything to share.  Ours does (recently) support sub-tests.

@yilei and @rickeylev as FYI on the absl-py side.

**Comment by dnozay** [comment]
Contributions are welcome, @gpshead.
