### ISSUE TITLE
Recording the version of the Unit Under Test in the junit.xml

### ISSUE THREAD

**Issue by Costas-Zervos-CardinalPeak** [xmlrunner/unittest-xml-reporting#207]
Our setup is 

1. using unittest to execute the automated portion of our test plan
2. utilize the xml-runner as a test runner so that we can get the test results outputs formatted in junit.xml format
3. use unitrail to post the results onto TestRail

The above works out of the box but has shortcomings in that we can't push custom fields/attributes to TestRail since they are not present in the junit.xml file generated.

For example let's say we want to record the firmware version of the Unit Under Test for each test case.  One way I thought of doing this is to add the attribute "version" to the <testcase> and have unitrail read it from there and post it to TestRail.  I have manually edited a junit.xml file to include this additional attribute 
<testcase classname="Test_Uart" file="test_Uart.py" line="51" name="test_init" time="0.003" timestamp="2020-01-02T16:46:24" version="v1.3.4 (from attribute)">
and verified that my modified unitrail does consume and correctly posts to TestRail.

The challenge I am facing is how to get unittest and xmlrunner to write this attribute to the junit.xml file.  As I write this I recognize that by adding this "version" attribute to testcase I may be violating the junit schema and thus this might not be the recommended way to go.  Having said that  junitparser allows you to do exactly this.

If I can't add this custom attribute to the junit.xml file I am left with the option of printing the version while executing the test (thus ending up with the version of the UUT in the <system-out> child of test case and I can do some sort of regex processing in my unitrail to extract it.

I don't like this option because

1. it clutters the console output when executing the tests and
2. it makes the unitrail code somewhat more complicated.

Is having the firmware version of the Unit Under Test a reasonable item to want to record in the junit.xml file and if yes what is the recommended way for doing so with  xmlrunner and unittest?

TIA,

Costas

**Comment by dnozay** [comment]
https://github.com/xmlrunner/unittest-xml-reporting/blob/6336fe8914f086fb87dd5e4570b876269e28c6d1/tests/testsuite.py#L638-L643

If you use your own test loader and add properties on the testsuite, then they will get reported.
