### ISSUE TITLE
ValueError Exception Importing result._XMLTestResult

### ISSUE THREAD

**Issue by arossi1** [xmlrunner/unittest-xml-reporting#213]
I don't have a good reproducer that I can publish publicly yet, but I would like to post this issue now so the team has it.  The high level steps are:

1. create new python 2.7 conda virtual environment
2. pip install `unittest-xml-reporting` (v.3.0)
3. conda install additional packages

Note: if I pin the pip install of `unittest-xml-reporting` to v2.5.2, everything works fine (i.e., I don't get the exception below).

```
File "/lib/python2.7/site-packages/xmlrunner/__init__.py", line 11, in <module>
    from .runner import XMLTestRunner
File "lib/python2.7/site-packages/xmlrunner/runner.py", line 7, in <module>
    from .result import _XMLTestResult
File "lib/python2.7/site-packages/xmlrunner/result.py", line 42, in <module>
    for (low, high) in _illegal_unichrs
ValueError: chr() arg not in range(256)
```

**Comment by dnozay** [comment]
Please note Python 2.7 end-of-life was in Jan 2020, last version supporting 2.7 was 2.5.2

**Comment by arossi1** [comment]
Fair enough - is there any way to prevent the Python 2 incompatible version (>=3.0) from being installed in Python 2 environments?  Perhaps by defining pip package dependencies?  Thanks!

**Comment by devinrsmith** [comment]
I would suggest deleting the 3.0.0 release on PyPi (https://pypi.org/project/unittest-xml-reporting/3.0.0/), otherwise Python 2 pip clients will continue to download it.
