### ISSUE TITLE
[3.0.2] "An invalid XML character (Unicode: 0xc) was found in the comment."

### ISSUE THREAD

**Issue by felixxm** [xmlrunner/unittest-xml-reporting#217]
It looks that there is a regression in `unittest-xml-reporting==3.0.2`. We're getting:
```
Failed to read test report file /home/jenkins/workspace/pull-requests-bionic/database/postgis/label/bionic-pr/python/python3.7/tests/TEST-i18n.test_extraction.LocationCommentsTests-20200224013040.xml
org.dom4j.DocumentException: Error on line 36 of document  : An invalid XML character (Unicode: 0xc) was found in the comment.
```
that doesn't appear with 3.0.1 (see [related tests](https://github.com/django/django/blob/0352a44dd61c19bebf0c0b305dbbc3f710ff9945/tests/i18n/test_extraction.py#L576-L637)). Diff between generated XMLs is showing extra characters in the `<system-out>` and `<system-err>` nodes, e.g.:

- 3.0.1:
```xml
<testcase classname="i18n.test_extraction.LocationCommentsTests" name="test_no_location_disabled" time="0.170" timestamp="2020-02-24T02:05:03" file="i18n/test_extraction.py" line="584">
        <system-out><![CDATA[]]></system-out>
        <system-err><![CDATA[]]></system-err>
</testcase>
```
- 3.0.2:
```xml
<testcase classname="i18n.test_extraction.LocationCommentsTests" file="i18n/test_extraction.py" line="584" name="test_no_location_disabled" time="0.220" timestamp="2020-02-12T09:55:02">
        <system-out>
<![CDATA[]]>            </system-out>
        <system-err>
<![CDATA[]]>            </system-err>
</testcase>
```

**Comment by dnozay** [comment]
```
An invalid XML character (Unicode: 0xc) was found in the comment.
```
- I did check a hexdump, and the expected characters are `0x0a` (or `\n`) and `0x09` (or `\t`) which correspond to the `.toprettyxml()` from `xml.dom.minidom`
- "`was found in the comment.`" sounds suspicious, where is the comment?

**Comment by felixxm** [comment]
I don't see anything unusual in this test, see [test_no_location_disabled()](https://github.com/django/django/blob/632ccffc49658de5348c51a8918719364be54f37/tests/i18n/test_extraction.py#L594-L599).

**Comment by felixxm** [comment]
@dnozay Thanks :rocket:
