### ISSUE TITLE
3.0.1 version not found in pipy

### ISSUE THREAD

**Issue by pymen** [xmlrunner/unittest-xml-reporting#224]
$ pip install unittest-xml-reporting==3.0.1                                                                                                                                         ~/p/n/api 1
ERROR: Could not find a version that satisfies the requirement unittest-xml-reporting==3.0.1 (from versions: 1.0, 1.0.1, 1.0.2, 1.0.3, 1.2, 1.3, 1.3.1, 1.3.2, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.14.0, 2.0.0a0, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.3.1, 2.3.2, 2.4.0, 2.5.0, 2.5.1, 2.5.2, 3.0.2)
ERROR: No matching distribution found for unittest-xml-reporting==3.0.1

**Comment by dnozay** [comment]
Sorry about that, I've removed 3.0.0 and 3.0.1 from pypi when processing #212 .
Please upgrade to 3.0.2.

**Comment by pymen** [comment]
thanks for answer
