### ISSUE TITLE
Troublesome instructions in readme

### ISSUE THREAD

**Issue by Talispaehn** [xmlrunner/unittest-xml-reporting#226]
Hi,

Under the 'Reporting to a single file' topic, you have the output mode defined as 'wb', this will fail with the error 
"TypeError: a bytes-like object is required, not 'str'"

The correct mode would be 'w' , to ensure no failure.

Relevant issue from stackoverflow (found after trying through your readme): 
https://stackoverflow.com/questions/33054527/typeerror-a-bytes-like-object-is-required-not-str-when-writing-to-a-file-in

**Comment by dnozay** [comment]
@Talispaehn do you have some code to reproduce this error?

**Comment by Talispaehn** [comment]
Will try to find the time and (re)create the code.
