### ISSUE TITLE
Add support for latest stable Python and Django versions

### ISSUE THREAD

**Issue by pauloxnet** [xmlrunner/unittest-xml-reporting#262]

**Comment by dnozay** [comment]
@pauloxnet - did you find #258 sufficient or would you like to send a pull request?

**Comment by pauloxnet** [comment]
I'll try to send ASAP a new PR

**Comment by pauloxnet** [comment]
@dnozay you were too fast.

However, I opened the PR #266 where I updated the versions of Python and Django.

In particular:
- I removed python 3.5 and 3.6 which have reached end of life.
- I added in Python 3.9 and 3.10 tests.
- I have updated the version of Django 4.0

**Comment by dnozay** [comment]
@pauloxnet Thank you.
