### ISSUE TITLE
Feature request: option for "unexpected success" to show up as failure

### ISSUE THREAD

**Issue by zou3519** [xmlrunner/unittest-xml-reporting#263]
Unexpected successes currently do not seem to show up in the xml. For example, the following script's xml output ignores the unexpected success and only reports the failures.

We're using xmlrunner in conjunction with CircleCI to log which tests are failing. Today, when the CI for our project fails due to an unexpected success, CircleCI does not tell us which tests are failing and we need to manually check the logs to identify them.

It would be really cool if there were an option for unexpected successes to show up as failed tests in the XML test output.

```
import unittest
import xmlrunner

class TestSomething(unittest.TestCase):
    def test_a(self):
        pass

    @unittest.expectedFailure
    def test_b(self):
        return


if __name__ == '__main__':
    unittest.main(
        testRunner=xmlrunner.XMLTestRunner(output='test-reports'),
        # these make sure that some options that are not applicable
        # remain hidden from the help menu.
        failfast=False, buffer=False, catchbreak=False)
```
creates the following output:
```
<?xml version="1.0" ?>
<testsuite name="TestSomething-20211214122930" tests="1" time="0.000" failures="0" errors="0">
  <testcase classname="TestSomething" name="test_a" time="0.000"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```

**Comment by dnozay** [comment]
@zou3519 , I do not have much time to work on the project these days, but I will consider merging a pull request if that is something you could help with.

**Comment by samdow** [comment]
Hi @dnozay, this was actually an install error--we were accidentally on an older version of this package and this is supported in the latest version, so feel free to close the issue. And thanks so much for this project, it's really helped us out!
