### ISSUE TITLE
XML reports not generated when running tests using unittest discovery

### ISSUE THREAD

**Issue by betrcode** [xmlrunner/unittest-xml-reporting#66]
When I run tests using `python -m unittest discover` the generation of XML reports is not triggered.

This is assuming I have setup my test module like this:

```
import unittest
import xmlrunner
...

class SomeTest(unittest.TestCase):
...


if __name__ == '__main__':
    unittest.main(testRunner=xmlrunner.XMLTestRunner(output='test-reports'))
```

The reason seems to be that when unit tests are run using the discovery feature, __main__ of module is not being run.

Is there another way of making this work?

Thanks for all your efforts.

**Comment by betrcode** [comment]
@dnozay Is it possible to make it use a custom test runner? 
The thing I like with the discovery is that I do not have to know which test modules exist. It will find them for me.

**Comment by dnozay** [comment]
Test discovery is documented here: https://docs.python.org/2/library/unittest.html#load-tests-protocol
You should be able to modify your script to do the same.

**Comment by chrisheaththomas** [comment]
@dnozay Implementing a load_tests method allows you to return a TestSuite but not a custom TestRunner.

**Comment by cvrajeesh** [comment]
This is how I made it to work; created `tests/main.py` with following lines, then executed it by calling `python tests/main.py` instead of `python -m unittest discover`

```
import os
import unittest
import xmlrunner

if __name__ == '__main__':
    root_dir = os.path.dirname(__file__)
    test_loader = unittest.TestLoader()
    package_tests = test_loader.discover(start_dir=root_dir)

    testRunner = xmlrunner.XMLTestRunner(output='test-reports')
    testRunner.run(package_tests)
```

**Comment by JoePercipientAI** [comment]
@cvrajeesh I tried this, but when I run the command `python tests/main.py`, my imports in my test file fail with "ModuleNotFoundError".

I tried adding -m to the command `python -m tests/main.py`, but then I get "usr/bin/python: Import by filename is not supported."

When I try it with python3 `python3 -m tests/main.py`, I get "Error while finding module specification for 'tests/main.py' (ModuleNotFoundError: No module named 'tests/main')"

Any thoughts on how I can make this work?

**Comment by xdhmoore** [comment]
@JoePercipientAI Well, it's more than a year later, but mine seems to work if I invoke it "module-style": `python -m tests.main`

**Comment by xdhmoore** [comment]
Another note. With the above code snippet, test failures will not return a non-zero exit code. Adding the following fixes that:

```
import os
import unittest
import xmlrunner
import sys


if __name__ == '__main__':
    root_dir = os.path.dirname(__file__)
    test_loader = unittest.TestLoader()
    package_tests = test_loader.discover(start_dir=root_dir)

    testRunner = xmlrunner.XMLTestRunner(output='test-reports')
    result = testRunner.run(package_tests)
    if(not result.wasSuccessful()):
       sys.exit(1)
```
