### ISSUE TITLE
unittest.TestCase.subTest support (python 3.4+)

### ISSUE THREAD

**Issue by simbs** [xmlrunner/unittest-xml-reporting#77]
I am using subtests within some of my test methods, and xmlrunner doesn't fully support them.
It works just fine when all tests pass, but when one of them fails I get an error about not being able to get `self.elapsed_time()`, and no xml file is generated. Would it be possible to add this feature?

I also noticed that your runner is importing "unittest" for Python 3, when I am using unittest2. In xmlrunner/__init__.py, in the rewrite branch:

    if sys.version_info < (2, 7):
        # monkey patch unittest
        import unittest2 as unittest

and this in the master branch for xmlrunner/unittest.py  (I think I am using this, I downloaded it through pip)

    if sys.version_info < (2, 7):
        # pylint: disable-msg=W0611
        import unittest2 as unittest
 (...)
    else:
        # pylint: disable-msg=W0611
        import unittest

I've also been looking through the code to figure out if this is something I could do myself, and it seems that what is missing is a parent context for the subtests. They should have an index attribute, and no elapsed time, since that is only recorded for the full test (is it?). Don’t really know where to start tho, I just started using unittest very recently.

**Comment by dnozay** [comment]
`unittest.TestCase.subTest()` is new in python 3.4; it definitely is not supported by `unittest2` at this time. It probably will never be supported in `unittest2` as it is a port of newer unittest features in python 2.7+ for python < 2.7. However python 2.6 is no longer supported (end-of-life).

Another point is that I am not sure how you would represent sub-tests in the xUnit schema.
Here is a link to [a junit xsd](https://svn.jenkins-ci.org/trunk/hudson/dtkit/dtkit-format/dtkit-junit-model/src/main/resources/com/thalesgroup/dtkit/junit/model/xsd/junit-4.xsd).
