### ISSUE TITLE
When running in Jython I get the following error  UnicodeDecodeError ( 'unicodeescape' codec can't decode bytes in position 29-35: illegal Unicode character )

### ISSUE THREAD

**Issue by cmodien** [xmlrunner/unittest-xml-reporting#79]
I'm working on submitting a patch for this.  Here is the offending line in result.py
u'[\x00-\x08\x0B\x0C\x0E-\x1F\uD800-\uDFFF\uFFFE\uFFFF]'

**Comment by dnozay** [comment]
* http://stackoverflow.com/questions/1707890/fast-way-to-filter-illegal-xml-unicode-chars-in-python
* https://github.com/html5lib/html5lib-python/issues/2

please check #82.
