### ISSUE TITLE
XMLTestRunner not honoring failfast

### ISSUE THREAD

**Issue by kellerb** [xmlrunner/unittest-xml-reporting#87]
Based on examining `TextTestRunner`, it appears that after [creating](https://github.com/xmlrunner/unittest-xml-reporting/blob/6a914bdade64d63a47209db7d34ea29c61dfe572/xmlrunner/runner.py#L47) the `result` object in `XMLTestRunner.run`, there should be a `result.failfast = self.failfast`.

**Comment by PhilipGarnero** [comment]
:+1: Failfast is needed
