### ISSUE TITLE
Generate a single xml report

### ISSUE THREAD

**Issue by IlkerDemir** [xmlrunner/unittest-xml-reporting#89]
Hi all,

Is there a way to generate one xml report per suite using xmlrunner?

I do not think that I am loading my test cases into the suite wrongly (I have my suite containing the associated test cases).
But I can't have one report generated for the whole test suite, xmlrunner seems to consider my test cases as test suites.

Is it simply not possible or is there a particular way for loading the test cases into the suite?

I think I tried all the different possibilities for loading the test cases into the test suite but the result was always the same.

Thanks in advance

Ilker

**Comment by tmatthias-cntient** [comment]
I have this same issue, I have numerous TestCase files and am adding them to a single TestSuite, but when I run xmlrunner.XMLTestRunner, I get an xml file for every single TestCase (there are a lot) with the exact same output in each.

**Comment by dnozay** [comment]
see #44

**Comment by dnozay** [comment]
```python
    with open('/path/to/results.xml', 'wb') as output:
        unittest.main(
            testRunner=xmlrunner.XMLTestRunner(output=output),
            failfast=False, buffer=False, catchbreak=False)
```

**Comment by rajattibco123** [comment]
@dnozay  I am getting this error while running multiple py files in unittest 
with open(baseCLI.reportsPath+'/results.xml', 'wb') as output:
                 xmlrunner.XMLTestRunner(output=output,verbosity=2).run(big_suite)

The error says:
TypeError: a bytes-like object is required, not 'str'

**Comment by Zergoks** [comment]
@rajattibco123 If you are Windows user. Try to replace 'wb' with 'w+'
