### ISSUE TITLE
processing Python doctests?

### ISSUE THREAD

**Issue by gliptak** [xmlrunner/unittest-xml-reporting#94]
Would unittest-xml-reporting process Python doctests? I didn't seem to see references in the documentation. Thanks

**Comment by dnozay** [comment]
It may not work out of the box as both `xmlrunner` and `doctest` use their own test runner; but nothing prevents you to subclass the `doctest` runner to do the same.

* https://docs.python.org/2/library/doctest.html#unittest-api
* https://docs.python.org/2/library/doctest.html#advanced-api

**Comment by gliptak** [comment]
Could xmlrunner be extended to cover doctests? Thanks

**Comment by dnozay** [comment]
pull requests welcome.

**Comment by gliptak** [comment]
The support might already be almost there. I created a small example of doctest processing.
```
"""
This is the "example" module.

The example module supplies one function, twice().  For example,

>>> twice(5)
10
"""

def twice(n):
    return 2*n


if __name__ == "__main__":
    import doctest
    import unittest
    import xmlrunner
    #doctest.testmod()
    tests = doctest.DocTestSuite()
    print("+++Running TextTestRunner")
    unittest.TextTestRunner().run(tests)
    print("+++Running XMLTestRunner")
    unittest.main(tests, testRunner=xmlrunner.XMLTestRunner())
```

XMLTestRunner doesn't see the test (while TextTestRunner does):

```
+++Running TextTestRunner
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
+++Running XMLTestRunner

Running tests...
----------------------------------------------------------------------

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Generating XML reports...
```

**Comment by dnozay** [comment]
providing the testsuite generated by `doctest.DocTestSuite` to the `xmlrunner.XMLTestRunner` works.

**Comment by gliptak** [comment]
https://github.com/xmlrunner/unittest-xml-reporting/pull/100
